version: '3.8'

services:
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: devops

